language: node_js
node_js:
  - "8"
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

# Reduce how often send emails
notifications:
  email:
    on_success: never
    on_failure: change
